repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        language: system
        types: [python]
        require_serial: true
        args: [--check, --diff]
-   repo: local
    hooks:
    -   id: ruff
        name: ruff
        entry: ruff
        language: system
        types: [python]
        require_serial: true
        args: [check]