repos:
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
-   repo: https://github.com/pycqa/pylint
    rev: v2.15.5
    hooks:
    -   id: pylint
        args: [--rcfile=.pylintrc]