'''
Titan2: Globals
'''

CRLF = "\r\n"

GEMINI_SCHEME = 'gemini'
GEMINI_PORT = 1965
GEMINI_DEFAULT_MIME_TYPE = 'text/gemini; charset=utf-8'
GEMINI_DEFAULT_ENCODING = 'utf-8'
GEMINI_RESPONSE_HEADER_SEPARATOR = ' '
GEMINI_URL_MAXLENGTH = 1024
GEMINI_RESPONSE_HEADER_META_MAXLENGTH = 1024

REQUEST_DEFAULT_TIMEOUT = 30

RESPONSE_STATUS_ERROR = "0"
RESPONSE_STATUS_INPUT = "1"
RESPONSE_STATUS_SUCCESS = "2"
RESPONSE_STATUS_REDIRECT = "3"
RESPONSE_STATUS_TEMP_FAILURE = "4"
RESPONSE_STATUS_PERM_FAILURE = "5"
RESPONSE_STATUS_CLIENTCERT_REQUIRED = "6"

RESPONSE_STATUSDETAIL_ERROR_UNKNOWN_HOST = "00" 
RESPONSE_STATUSDETAIL_ERROR_TIMEOUT = "01"
RESPONSE_STATUSDETAIL_ERROR_REFUSED = "02"
RESPONSE_STATUSDETAIL_ERROR_HOST_ERROR = "03"
RESPONSE_STATUSDETAIL_ERROR_RESET = "04"
RESPONSE_STATUSDETAIL_ERROR_SSL_HANDSHAKE = "05"
RESPONSE_STATUSDETAIL_ERROR_BAD_RESPONSE = "08"
RESPONSE_STATUSDETAIL_INPUT = "10"
RESPONSE_STATUSDETAIL_INPUT_SENSITIVE = "11"
RESPONSE_STATUSDETAIL_SUCCESS = "20"
RESPONSE_STATUSDETAIL_REDIRECT_TEMPORARY = "30"
RESPONSE_STATUSDETAIL_REDIRECT_PERMANENT = "31"
RESPONSE_STATUSDETAIL_TEMP_FAILURE = "40"
RESPONSE_STATUSDETAIL_TEMP_FAILURE_UNAVAILABLE = "41"
RESPONSE_STATUSDETAIL_TEMP_FAILURE_CGI = "42"
RESPONSE_STATUSDETAIL_TEMP_FAILURE_PROXY = "43"
RESPONSE_STATUSDETAIL_TEMP_FAILURE_SLOW_DOWN = "44"
RESPONSE_STATUSDETAIL_PERM_FAILURE = "50"
RESPONSE_STATUSDETAIL_PERM_FAILURE_NOT_FOUND = "51"
RESPONSE_STATUSDETAIL_PERM_FAILURE_GONE = "52"
RESPONSE_STATUSDETAIL_PERM_FAILURE_PROXY_REFUSED = "53"
RESPONSE_STATUSDETAIL_PERM_FAILURE_BAD_REQUEST = "59"
RESPONSE_STATUS_CLIENTCERT_REQUIRED = "60"
RESPONSE_STATUS_CLIENTCERT_REQUIRED_NOT_AUTHORIZED = "61"
RESPONSE_STATUS_CLIENTCERT_REQUIRED_NOT_VALID = "62"

