# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: "CI v2"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: python -m pip install .[lint]
      - name: black
        run: black --check .
      - name: ruff
        run: ruff check .
  test:
    name: "Python ${{ matrix.python-version}} Test"
    needs: [lint]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install .[test]
      - name: Test with pytest
        run: pytest --cov=ignition tests/
  check_status:
    name: "All Tests Passed Gate"
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - run: echo "All tests completed"
      
